/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Htree;

import java.awt.Graphics;

/**
 *
 * @author amina
 */
public class DrawingPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrawingPanel
     */
    public DrawingPanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g){
        Htree(g, 100, getWidth()/2, getHeight()/2, 3);
    }
    public void tree(Graphics g, int size, int x, int y) {
        
        // compute the coordinates of the 4 tips of the H
        int x0 = x - size/2;
        int x1 = x + size/2;
        int y0 = y - size/2;
        int y1 = y + size/2;

        // draw the 3 line segments of the H
        g.drawLine(x0, y0, x0, y1);    // left  vertical segment of the H
        g.drawLine(x1, y0, x1, y1);    // right vertical segment of the H
        g.drawLine(x0,  y, x1,  y);    // connect the two vertical segments of the H
        
    }
   
    public void Htree(Graphics g, int size, int x, int y, int n) {
        
        if (n == 0){
            return;
        }
        tree(g, size,x,y);
        // compute x- and y-coordinates of the 4 half-size H-trees
        int x0 = x - size/2;
        int x1 = x + size/2;
        int y0 = y - size/2;
        int y1 = y + size/2;

        // recursively draw 4 half-size H-trees of order n-1
        Htree(g, size/2, x0, y0,n-1);    // lower left  H-tree
        Htree(g, size/2, x0, y1, n-1);    // upper left  H-tree
        Htree(g,size/2, x1, y0, n-1);    // lower right H-tree
        Htree(g, size/2, x1, y1, n-1);    // upper right H-tree
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
